CREATE DATABASE QLVT;
USE Bai3;
-- Bảng NHANVIEN
CREATE TABLE NHANVIEN (
    MANV INT PRIMARY KEY,
    HO VARCHAR(40) NOT NULL,
    TEN VARCHAR(10) NOT NULL,
    PHAI VARCHAR(3) DEFAULT 'Nam' CHECK (PHAI IN ('Nam', 'Nữ')),
    DIACHI VARCHAR(50) NOT NULL DEFAULT ' ',
    NGAYSINH DATE,
    LUONG REAL DEFAULT 800000 CHECK (LUONG BETWEEN 800000 AND 6000000),
    GHICHU VARCHAR(80)
);

-- Bảng KHO
CREATE TABLE KHO (
    MAKHO CHAR(2) PRIMARY KEY,
    TENKHO VARCHAR(30) UNIQUE,
    DIACHI VARCHAR(70) NOT NULL
);

-- Bảng VATTU
CREATE TABLE VATTU (
    MAVT CHAR(4) PRIMARY KEY,
    TENVT VARCHAR(30) UNIQUE,
    DVT VARCHAR(15) DEFAULT ' '
);

-- Bảng PHATSINH
CREATE TABLE PHATSINH (
    PHIEU CHAR(8) PRIMARY KEY,
    NGAY DATE DEFAULT GETDATE(),
    LOAI CHAR DEFAULT 'N' CHECK (LOAI IN ('N', 'X', 'T', 'C')),
    HOTEN_KH VARCHAR(40) DEFAULT ' ',
    THANHTIEN REAL DEFAULT 0,
    MANV INT,
    LYDO VARCHAR(30),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

-- Bảng CT_PHATSINH
CREATE TABLE CT_PHATSINH (
    PHIEU CHAR(8),
    MAVT CHAR(4),
    SOLUONG INT CHECK (SOLUONG > 0),
    DONGIA REAL CHECK (DONGIA > 0),
    MAKHO CHAR(2),
    PRIMARY KEY (PHIEU, MAVT),
    FOREIGN KEY (PHIEU) REFERENCES PHATSINH(PHIEU),
    FOREIGN KEY (MAVT) REFERENCES VATTU(MAVT),
    FOREIGN KEY (MAKHO) REFERENCES KHO(MAKHO)
);
-- Danh sách những nhân viên từ 25 tuổi trở lên:
SELECT * FROM NHANVIEN WHERE DATEDIFF(YEAR, NGAYSINH, GETDATE()) >= 25;
-- Đếm số lượng nhân viên theo từng phái:
SELECT PHAI, COUNT(*) AS SoLuong FROM NHANVIEN GROUP BY PHAI;
--Danh sách những nhân viên có lương cao nhất:
SELECT * FROM NHANVIEN WHERE LUONG = (SELECT MAX(LUONG) FROM NHANVIEN);
--Danh sách những vật tư có chi tiết phát sinh:
SELECT DISTINCT V.MAVT, V.TENVT
FROM VATTU V
INNER JOIN CT_PHATSINH C ON V.MAVT = C.MAVT;
--Cập nhật thành tiền cho từng phiếu (thành tiền = sum(số lượng * đơn giá)):
UPDATE PHATSINH
SET THANHTIEN = (SELECT SUM(SOLUONG * DONGIA) FROM CT_PHATSINH WHERE PHIEU = PHATSINH.PHIEU);

